version: '2'

services:
  database:
    image: postgres:9.5
    networks:
      - auth-service

  auth-service:
    image: registry.nejla.com/nejla-ab/auth-service/auth-service
    links:
      - database
    environment:
      - log=true
      - TWILIO_ACCOUNT=
      - TWILIO_TOKEN=
      - TWILIO_SOURCE=
    # logging:
    #   driver: gelf
    #   options:
    #     gelf-address: udp://localhost:12201
    networks:
      - auth-service
    command: /app/run.sh

  # One or more application container`
  upstream:
    image: nginx:latest
    volumes:
      - ./tests/index.html:/www/index.html
      - ./tests/foo.html:/www/foo/index.html
      - ./tests/upstream-nginx.conf:/etc/nginx/nginx.conf
    networks:
      - auth-service

  auth-web:
    build: web
    links:
      - auth-service
      # Link upstream containers to their instance IDs
      - upstream:de305d54-75b4-431b-adb2-eb6b9e546014
    environment:
  #   - COOKIE=session
      - COOKIE=permanent
    networks:
      - auth-service
    volumes:
      - ./auth:/www/authentication

  frontend:
    image: nginx:latest
    # s/8000/<desired port>
    ports:
      - 8000:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/auth-service.include:/etc/nginx/auth-service.include
      - ./tests/index.html:/www/index.html
      - ./tests/foo.html:/www/foo.html
    links:
      - auth-web
    networks:
      - auth-service

networks:
  auth-service:
