name: auth-service
version: '0.0.0'
synopsis: Auth service
description: Auth service
copyright: '2015'
license: AllRightsReserved
extra-source-files:
- src/schema

library:
  source-dirs:
  - client
  - src
  ghc-options:
  - -Wall
  - -O2
  - -Werror=incomplete-patterns
  exposed-modules:
  - Api
  - Audit
  - AuthService
  - Backend
  - Config
  - Logging
  - Monad
  - Persist.Migration
  - Persist.Schema
  - Persist.Stage
  - Run
  - Twilio
  - Types
  - User
  - PasswordReset
  dependencies:
  - base >=4 && <5
  - aeson
  - auth-service-types
  - base64-bytestring >=1.0
  - bcrypt
  - bytestring
  - bytestring-conversion >=0.3
  - case-insensitive
  - configurator
  - containers
  - data-default
  - esqueleto
  - exceptions >=0.8
  - http-api-data >=0.2
  - http-conduit >=2.1
  - http-types >=0.9
  - lens
  - microstache
  - mime-mail
  - monad-logger >=0.3
  - mtl >=2.2
  - nejla-common
  - network
  - path-pieces
  - persistent >=2.2
  - persistent-postgresql >=2.2
  - persistent-template >=2.1
  - random >=1.1
  - servant-server >=0.4.4
  - template-haskell
  - text
  - time >=1.5
  - uuid >=1.3
  - wai >=3.0
  - warp

executables:
  auth-service:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -Wall
    - -O2
    dependencies:
    - base
    - auth-service

tests:
  api-tests:
    main: Test/Api.hs
    other-modules:
      - Test.Common
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - base
    - bytestring
    - QuickCheck
    - auth-service
    - exceptions >=0.8
    - hspec
    - hspec-core
    - hspec-expectations
    - hspec-wai
    - hspec-wai-json
    - interpolate
    - lens
    - microstache
    - monad-logger >=0.3
    - mtl >=2.2
    - nejla-common
    - persistent
    - persistent-postgresql
    - persistent-sqlite
    - resource-pool
    - text
    - time
    - unliftio-core
    - uuid
    - wai
    - wai-extra
    - data-default

  unit-tests:
    main: Test.hs
    other-modules:
      - Test.Common
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - base
    - QuickCheck
    - auth-service
    - data-default
    - exceptions >=0.8
    - hspec-expectations
    - hspec-wai
    - lens
    - microstache
    - monad-logger >=0.3
    - mtl >=2.2
    - nejla-common
    - persistent
    - persistent-sqlite
    - persistent-postgresql
    - resource-pool
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-th
    - text
    - time
    - unliftio-core
    - uuid
