resolver: lts-10.3

packages:
  - location: '.'
  - location: '../auth-service-types'
    extra-dep: true
  - location:
      git: git@git.nejla.com:nejla-ab/common.git
      commit: 2fc66571821282993095a13dd2d97329c0a68ac0
    extra-dep: true

image:
  container:
    name: "auth-service"
    base: "auth-service-baseimage"
    add:
      docker/add: /app
