resolver: lts-14.27

extra-deps:
  - git: git@git.nejla.com:nejla-ab/common.git
    commit: 65adf85e5e25274f31564e8efa2a48f581633734
  - '../auth-service-types'


docker:
  enable: false
  image: nejla/haskell-build

nix:
  packages:
    - zlib
    - postgresql
