# When resolver is changed, update .github/workflows/build.yaml and
# stack.dockerhub.yaml. When dependencies are updated, also update
# stack.dockerhub.yaml.

resolver: lts-18.12

extra-deps:
  - git: git@git.nejla.com:nejla-ab/common.git
    commit: 3cbc5d0db2e8c18838159b92d7bb9b39f551e226
  - '../auth-service-core'
  - base64-bytestring-1.2.0.1
  - git: https://github.com/mbg/wai-saml2.git
    commit: 5d0efb965dce1e6a6a2d446fa1b089465f00f0cf

docker:
  enable: false
  image: nejla/haskell-build

allow-newer: true

nix:
  # shell-file: stack.nix
  packages:
    - zlib
    - postgresql
    - pkg-config
    - libxml2
    - openssl
