##############################################
# NB: Changes to this file shold be reflected
# in stack.dockerhub.yaml !
##############################################

resolver: lts-22.12

extra-deps:
  - git: git@git.nejla.com:nejla-ab/common.git
    commit: 00713d27493f04d88a5637968f65a0cd474cd9b8
  - '../auth-service-core'

docker:
  enable: false
  image: nejla/haskell-build

allow-newer: true

nix:
  shell-file: ../shell.nix
