resolver: lts-18.12

extra-deps:
  - git: git@git.nejla.com:nejla-ab/common.git
    commit: 7a76b3253d31b0f23b1bf42681ca8e6d911006cb
  - '../auth-service-core'
  - base64-bytestring-1.2.0.1

docker:
  enable: false
  image: nejla/haskell-build

allow-newer: true

nix:
  # shell-file: stack.nix
  packages:
    - zlib
    - postgresql
