#!/usr/bin/env bash

set -e

fail() {
  echo "$*" >&2
  exit 1
}

[[ -n $CI_REGISTRY ]] || fail "CI_REGISTRY is undefined"
[[ -n $CI_JOB_TOKEN ]] || fail "CI_JOB_TOKEN is undefined"
docker login -u gitlab-ci-token -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
