#!/usr/bin/env bash

set -e

[[ -n $REGISTRY ]] || fail "REGISTRY is undefined"
[[ -n $CI_BUILD_TOKEN ]] || fail "CI_BUILD_TOKE is undefined"
docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
